---
name: Prep
on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "PDK Release prep"
        uses: hsnodgrass/pdk_release@v1
        with:
          release-action: 'prep'
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
